mysql:
  host:           ssh.guanxingtuan.top
  port:           3307
  db:             userdb
  user:           root
  password:       ytt@2023
  log_level:      dev


logger:
  level:          info
  prefix:         '[gin_study]'
  show_line:      true
  log_in_console: true

system:
  host:           "127.0.0.1"
  port:           8080
  env:            release