mysql:
  host:           127.0.0.1
  port:           3306
  db:             user
  config:         "parseTime=true"
  user:           root
  password:       1234
  log_level:      dev


logger:
  level:          info
  prefix:         '[gin_study]'
  show_line:      true
  log_in_console: true

system:
  host:           "127.0.0.1"
  port:           8080
  env:            release