mysql:
  host:           ssh.guanxingtuan.top
  port:           3307
  db:             userdb
  config:         "parseTime=true"
  user:           root
  password:       ytt@2023
  log_level:      dev


system:
  host:           "127.0.0.1"
  port:           8080
  env:            release
  
AccessKeyID: Q4yKxNBy8nvZ9kCsgwTYmq4xnAKTrqbVuN66sEwxyjfCCoLGL
key: "mY9bY4xN4f"