mysql:
  host:           127.0.0.1
  port:           3306
  db:             gintest
  config:         "parseTime=true"
  user:           root
  password:       123456
  log_level:      dev


system:
  host:           "127.0.0.1"
  port:           8080
  env:            release